version: '3'
services:
 
  fastapi-backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - ELASTIC_SEARCH_URL=${ELASTIC_SEARCH_URL}
      - TOKEN=${TOKEN}
      - TZ=America/Bogota
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - elk
 
volumes:
  elasticsearch_data:
    driver: local
 
networks:
  elk:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.100.0/24